import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'john@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Ao thun nu trang',
      category: 'Shirts',
      image: '/images/2908202130846_1.jpg',
      price: '120',
      countInStock: 20,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Ao thun nu den',
      category: 'Shirts',
      image: '/images/2913202131345_1.jpg',
      price: '110',
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Ao thun nu xanh',
      category: 'Shirts',
      image: '/images/2915202131534_1.jpg',
      price: '150',
      countInStock: 5,
      brand: 'Lacoste',
      rating: 4.0,
      numReviews: 19,
      description: 'High quality product',
    },
    {
      name: 'Ao thun nu do',
      category: 'Shirts',
      image: '/images/2917202131755_1.jpg',
      price: '125',
      countInStock: 5,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 12,
      description: 'High quality product',
    },
    {
      name: 'Ao phong nam bien xanh',
      category: 'Shirts',
      image: '/images/13052021040523_Dai_dien.jpg',
      price: '120',
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 13,
      description: 'High quality product',
    },
    {
      name: 'Ao thun nam trang',
      category: 'Shirts',
      image: '/images/13052021100514_Dai_dien.jpg',
      price: '120',
      countInStock: 5,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 19,
      description: 'High quality product',
    },
    {
      name: 'Quan short nam',
      category: 'Pants',
      image: '/images/14052021030525_dai_dien.jpg',
      price: '125',
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Quan jean nam den',
      category: 'Pants',
      image: '/images/14052021030554_dai_dien.jpg',
      price: '90',
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Quan jean nam xanh',
      category: 'Pants',
      image: '/images/31032021090328_1.jpg',
      price: '140',
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 20,
      description: 'High quality product',
    },
  ],
};

export default data;
